version: '3'

services:
  ticket-tracker:
    build: .
    volumes:
      - ./data:/app/data  # Maps a local 'data' folder to container's data folder
    env_file:
    - .env
    environment:
      - DB_PATH=/app/data/ticket_history.db
